version: '3.8'

services:
  server:
    environment:
      - SERVER_USERNAME=username
      - SERVER_PASSWORD=secret_password
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./download_server:/app/downloads # Mounts the local 'download_server' folder to '/app/download' in the container
    networks:
      - app-network
  client:
    environment:
      - CLIENT_USERNAME=username
      - CLIENT_PASSWORD=secret_password
      - NUM_FILES_TO_CREATE=20   # Number of files to create in the 'data' folder
      - INDEX_TO_DOWNLOAD=10     # Index of the file to download from the server in the range [0, NUM_FILES_TO_CREATE-1]
      - MAX_RETRIES_UPLOAD=3     # Maximum number of retries to upload a file to the server      
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    depends_on:
      - server
    volumes:
      - ./data:/app/data        # Mounts the local 'data' folder to '/app/data' in the container
      - ./download_client:/app/downloads # Mounts the local 'download' folder to '/app/download' in the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
